### ISSUE TITLE
Minimal required rubocop version

### ISSUE THREAD

**Issue by nikolai-markov-workato** [rubocop/vscode-rubocop#11]
Hi!
First of all, thanks for finally making official vscode extension for rubocop 🙂
I hope it will work the best of all other extensions 🙂 

---

**Question:** Could I weak the minimum required version? E.g. to `1.41.0` (this is just a version I use in my work project)
https://github.com/rubocop/vscode-rubocop/blob/2a39c680002313b656b3f4d5a99128b256ef8d11/src/extension.ts#L235

**Comment by nikolai-markov-workato** [comment]
I see `1.53` is the version with LSP support 
<img width="678" alt="image" src="https://github.com/rubocop/vscode-rubocop/assets/121014301/8c62468a-f1a4-4cb6-b781-11774ba9a336">

**Comment by koic** [comment]
Yes, the built-in language server was introduced in RuboCop 1.53.
https://docs.rubocop.org/rubocop/usage/lsp.html
