### ISSUE TITLE
rubocop.yml config not registered

### ISSUE THREAD

**Issue by michaelwapp** [rubocop/vscode-rubocop#15]
Hi, 

It seems like the `rubocop.yml` file is not considered when using this extension. 

Any ideas? Do I need to configure it somehow specifically? 

VS Code Version: 1.83.1
Extension Version: v0.6.0

**Comment by koic** [comment]
The built-in language server was introduced in RuboCop 1.53.
https://docs.rubocop.org/rubocop/usage/lsp.html

Can you provide the result of `rubocop -V`?

**Comment by michaelwapp** [comment]
`1.56.2`

**Comment by koic** [comment]
> It seems like the `rubocop.yml` file is not considered when using this extension. 

Upon closer inspection, it seems to be `rubocop.yml`, not `.rubocop.yml`. Is there a leading `.` (dot) in front of it?

**Comment by michaelwapp** [comment]
There is no leading `.` (dot). Should it be there?

**Comment by koic** [comment]
Yes. RuboCop's configuration file is `.rubocop.yml`. Please try adding `.` (dot) at the leading.
https://docs.rubocop.org/rubocop/1.57/configuration.html

**Comment by michaelwapp** [comment]
Lovely, it's working now 🙏 Thank you!

**Comment by koic** [comment]
Good news! You are welcome!
