### ISSUE TITLE
[Feature Request] Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by isatsam** [rubocop/vscode-rubocop#16]
Due to Microsoft's ToS, VSCodium and other VSCode-based IDEs (Theia etc) cannot use the Microsoft extensions marketplace.
As open-vsx.org is the default marketplace in Codium, would it be possible to publish Rubocop there? 

([Related guide](https://www.gitpod.io/blog/open-vsx#publishing))
As a sidenote, [rubocop-revived](https://github.com/LoranKloeze/vscode-ruby-rubocop-revived) was published to open-vsx, but its repository was archived yesterday, so it would be nice to have an up-to-date/maintained rubocop extension in the registry still.

**Comment by koic** [comment]
Thank you for the feedback! vscode-rubocop has been published to Open VSX Registry:
https://open-vsx.org/extension/rubocop/vscode-rubocop

Enjoy Ruby with the LSP!
