### ISSUE TITLE
MethodLength and ClassLength indicate the whole method

### ISSUE THREAD

**Issue by kahnyoudiggit** [rubocop/vscode-rubocop#19]
When a method/class is indicated as too long, the entire method/class gets underlined with a squiggle. This can be problematic because 

- It obfuscates other linting issues
- When working in legacy code with many long methods/classes it can make parsing/referencing their behavior more difficult.
<img width="447" alt="Screenshot 2023-11-16 at 3 28 22 PM" src="https://github.com/rubocop/vscode-rubocop/assets/38542002/2ee98e94-aeb0-4b0c-88a5-736607ff84a9">

My suggestion is to have only the definition of the method/class be underlined, so that the rest of the content
 is readable

**Comment by nickooolas** [comment]
@koic - hope you are well! Just wondering regarding this one if you could lend some insights, this seems to be the standard way that rubocop operates when in VSCode using only this extension.

However, when reviewing offences via the CLI (ie `bundle exec rubocop file_here.rb`) it only lists the top of the method as the offence, and highlights just this part (ie method, or class name only). 

Is this a configuration thing is VSCode that is causing this, or is there no way to override this? I've noted that other VS Code rubocop extensions, work in the other manner consistent with CLI, and only show the first line highlighted, not the entire method/class, such as (https://github.com/misogi/vscode-ruby-rubocop).

Any insights into whether this is just how this will work, whether there is a way to change this, or understand at a minimum what is causing this experience? Thanks!

**Comment by koic** [comment]
This requires an update to RuboCop core feature, not LSP client side feature. It will be consolidated into issue https://github.com/rubocop/rubocop/issues/12676, which concerns the same issue.

**Comment by ozydingo** [comment]
@koic In our team, some folks use the [ruby-rubocop-revived](https://marketplace.visualstudio.com/items?itemName=LoranKloeze.ruby-rubocop-revived) VSCode plugin. FWIW, this plugin is able to keep highlighted sections limited 

![Screenshot 2023-11-16 at 07 10 44 (1)](https://github.com/rubocop/vscode-rubocop/assets/4616431/6367ebfc-907b-4739-acb4-2f947d98a295)

**Comment by koic** [comment]
Thank you for sharing the information. However, this issue is also occurring in Emacs, Neovim, and other LSP clients. It would be reasonable to solve the issue across all LSP clients by updating the language server itself, leveraging the feature of LSP.
