### ISSUE TITLE
It doesn't work with Rubocop 1.57.1 version

### ISSUE THREAD

**Issue by dbachinin** [rubocop/vscode-rubocop#20]
When I try to use it extension. I return this error in vscode.

```
[client] Disabling because the extension does not support this version of the rubocop gem.
[client]   Version reported by `/home/dbachinin/.rvm/gems/ruby-2.7.6/bin/rubocop -v`: Found no changes, using resolution from the lockfile
1.57.1 (>= 1.53.0 required)
```

**Comment by koic** [comment]
I'm interested in the output message of `Found no changes, using resolution from the lockfile`.

Can you provide the setting value from the link below, and the output results of running the `rubocop` command in your terminal for the specified repository?
https://github.com/rubocop/vscode-rubocop?tab=readme-ov-file#rubocopcommandpath

**Comment by koic** [comment]
I'll close this issue because it may be a similar problem to #21 or #22. Thank you.
