### ISSUE TITLE
Rubocop seems to be confused about versions says 1.59.0 is unsupported

### ISSUE THREAD

**Issue by alexrecuenco** [rubocop/vscode-rubocop#26]
When I restart RuboCop I get:

Unsupported RuboCop version: RuboCop server starting on 127.0.0.1:51109. 1.59.0 (>= 1.53.0 required)

**Comment by alexrecuenco** [comment]
And `semver` should be reporting it correctly. 
> s.satisfies('1.59.0', '>=1.53.0')
true

**Comment by alexrecuenco** [comment]
Ok, I found the problem, although the error message is misleading

It was unable to start the `rubocop --lsp` server, because it was already running from another extension

How it happened: 

I was confused with all the "rubocop" extension I had installed one called "rubocop revived", and when I uninstalled and reloaded vscode, that server was left running as a background task. I needed to manually `ps aux | grep rubocop` and then deleted it

**Comment by elliotcm** [comment]
In a similar vein it seems to report the same error if you have `--server` set in `.rubocop`, I guess it's trying to start with both `--server` and `--lsp` and gets unhappy.  Works OK with that removed.
